name: ticker_tape
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  linear_equations:
    path: ../../linear-equations

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
